name: HAMQTT Integration Workflow - Oxxio

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
    tags: [ 'v*.*.*' ]
    paths:
      - .github/workflows/oxxio.yml
      - .github/workflows/hamqtt-integration-workflow.yml
      - src/HAMQTT.Integration/**
      - src/HAMQTT.Integration.Oxxio/**
jobs:
  build:
    name: Integration Workflow
    uses: mavanmanen/HAMQTT/.github/workflows/hamqtt-integration-workflow.yml@main
    with:
      integration_name: Oxxio