name: HAMQTT Integration Workflow - Oxxio

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
    tags: [ 'v*.*.*' ]
    paths:
      - HAMQTT.Integration.Oxxio/**
jobs:
  build:
    uses: mavanmanen/.github/.github/workflows/hamqtt-integration-workflow.yml@main
    with:
      integration_name: Oxxio